### ISSUE TITLE
intermittent connection failures

### ISSUE THREAD

**Issue by zhuyifei1999** [zhuyifei1999/ishoal#4]
(ping @ionizer999)

So recently we are observing some intermittent connection failures, and I asked one whom I had connection failures with to do some testing, and we were able to reproduce it while capturing the packets by wireshark. We avoided all possibilities of having a IP collision by NAT-ing to a `192.168.99.*` at ishoal, and there's what we have, with the view of the capture limited to `192.168.99.*` subnet (compressed to zip because of github):

The host (them) at 192.168.99.222: [a1s.pcapng.zip](https://github.com/zhuyifei1999/ishoal/files/5100172/a1s.pcapng.zip)
The client (me) at 192.168.99.123: [m1s.pcapng.zip](https://github.com/zhuyifei1999/ishoal/files/5100174/m1s.pcapng.zip)

AFAICT, there is no packet loss or any shenanigans, but I did get the error of one or more consoles not responding, and I can't see what it is complaining about. Any ideas?

**Comment by ionizer999** [comment]
@zhuyifei1999 Did you ensure all UDP checksums are correct? It seems you need to activate that in wireshark first, before it highlights bad UDP checksums.

A bad UDP checksum could explain the problem.

**Comment by zhuyifei1999** [comment]
They are checked AFAICT. Packets with bad checksums are highlighted in
black IIRC and I don't see them in these captures.

**Comment by zhuyifei1999** [comment]
Actually, thinking about this again, during "VPN route" IP packets are wrapped in UDP. Ishoal has to do is, on the other side, unwrap the UDP packets. Nothing inside the inner IP should have been modified so there should be no checksum needs changing. Although yes the wrapper UDP + IP needs checksum computation (and as far as I'm aware, the checksums are ciorrect) but that shouldn't break the connection as long every IP packet sent from one switch is received by the other switch unmodified...

**Comment by zhuyifei1999** [comment]
Update: Last week, we tested this again. Still bad. Then we rolled back to a known-good version from July that did not do checksums properly. Still bad. Then we rolled back to your non-p2p solution, still bad. Since all the captures looks fine I just went, it can't be the connection between our VMs because the packet captures looks fine; it can't be the connection between my switch to my VM because it works fine when I play with others; it must be their VM and their switch. 

Later they changed to 5G from 2.4G and it just started working....

I should also document here, it works once they are in the room, it's just the act of joining a room that is really unstable.

**Comment by ionizer999** [comment]
That is fascinating: Maybe the Switch Wifi is faulty and can lead to packet loss and that explains all the "Connection unstable" messages?

**Comment by zhuyifei1999** [comment]
I don't know. As far as I have tested 'connection unstable' can usually be explained with something else, like bad checksum causing packet loss...

The thing is, in this incident connection unstable never appeared. it's always just plainly comm error or one or more console not responding, before joining the lobby. After joining lobby everything is stable. Just so weird...
